apiVersion: batch/v1
kind: CronJob
metadata:
  namespace: {{ include "laravel.fullname" . }}
  name: scheduler
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: scheduler
              image: {{ .Values.registry }}/{{ include "laravel.fullname" . }}/cli:latest
              command:
                - php
              args:
                - artisan
                - schedule:run
              envFrom:
                - configMapRef:
                    name: {{ include "laravel.fullname" . }}-config
          restartPolicy: Never
