apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ include "laravel.fullname" . }}
  name: fpmserver
  labels:
    {{- include "laravel.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.phpFpm.replicaCount }}
  selector:
    matchLabels:
      app: fpmserver
  template:
    metadata:
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
      labels:
        app: fpmserver
    spec:
      initContainers:
        - name: migrations
          image: "{{ .Values.registry }}/{{ include "laravel.fullname" . }}/fpmserver:latest"
          imagePullPolicy: "Always"
          command:
            - php
          args:
            - artisan
            - migrate
            - --force
          envFrom:
            - configMapRef:
                name: {{ include "laravel.fullname" . }}-config
      containers:
        - name: php-fpm
          image: "{{ .Values.registry }}/{{ include "laravel.fullname" . }}/fpmserver:latest"
          imagePullPolicy: "Always"
          ports:
            - containerPort: 9000
          lifecycle:
            postStart:
              exec:
                command: [ "/bin/sh", "-c", "php artisan route:cache" ]
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
