apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ include "laravel.fullname" . }}
  name: {{ include "laravel.fullname" . }}-queue-worker
  labels:
    {{- include "laravel.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: backend
      layer: queue_worker
  template:
    metadata:
      labels:
        tier: backend
        layer: queue_worker
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
    spec:
      containers:
        - name: {{ include "laravel.fullname" . }}-queue-worker
          envFrom:
            - configMapRef:
                name: {{ include "laravel.fullname" . }}-config
          image: {{ .Values.registry }}/{{ include "laravel.fullname" . }}/default-queue-worker:latest
          imagePullPolicy: Always
          command:
            - php
          args:
            - artisan
            - queue:work
            - --queue=default
            - --max-jobs=200
          ports:
            - containerPort: 9000
