apiVersion: v1
kind: Service
metadata:
  namespace: {{ include "laravel.fullname" . }}
  name: webserver
  labels:
    {{- include "laravel.labels" . | nindent 4 }}
spec:
  selector:
    tier: backend
    layer: webserver
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
