apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ include "laravel.fullname" . }}
  name: webserver
  labels:
    {{- include "laravel.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.webserver.replicaCount }}
  selector:
    matchLabels:
      tier: backend
      layer: webserver
  template:
    metadata:
      labels:
        tier: backend
        layer: webserver
    spec:
      containers:
        - name: webserver
          image: {{ .Values.registry }}/{{ include "laravel.fullname" . }}/webserver:lates
          imagePullPolicy: Always
          ports:
              - containerPort: 80
          env:
            # Inject the FPM Host as we did with Docker Compose
            - name: FPM_HOST
              value: fpmserver:9000
